// Mod-identity helpers — Phase 1 of the mod-identity refactor.
//
// Source of truth: data/poe2/mod_ids.json, generated by
// scripts/assign-mod-ids.py. Each unique mod display name maps to a
// stable ASCII id (lowercase snake_case). Side (PREFIX / SUFFIX) is
// encoded separately on each mod entry, not in the id.
//
// This module ports the Python slug recipe to JS so callers that
// need to resolve a fresh display string (e.g. a string typed by the
// user in the recipe DSL, or a mod name from a future scrape that
// hasn't been folded into mod_ids.json yet) can compute the id
// deterministically. The lookup-first / slugify-fallback API is
// `resolveModId(name, nameToId)` — prefers the curated map, falls
// back to recomputing.
//
// Kept pure (no DOM, no fetch). The data file is loaded by the game
// module and threaded through the store; this file just transforms
// names ↔ ids.

// Order matters: longer/more-specific patterns first so they match
// before the generic ' to ' filler-drop. Mirrors the Python
// SUBSTITUTIONS list — keep the two in sync.
const SUBSTITUTIONS = [
  ['maximum',       'max'],
  ['damage',        'dmg'],
  ['strength',      'str'],
  ['dexterity',     'dex'],
  ['intelligence',  'int'],
  ['critical',      'crit'],
  ['increased',     'inc'],
  ['energy shield', 'es'],
  [' resistance ',  ' _res '],
  [' resistance',   ' _res'],
  ['% inc ',        ' inc_'],
  [' to ',          ' '],
  [' of ',          ' '],
];

/**
 * Slugify a mod display name into the canonical id. Pure function;
 * deterministic for the same input. If the input is already an id
 * (lowercase snake_case ASCII), it's returned unchanged.
 *
 * @param {string} name
 * @returns {string} the slug, or '' if the input is empty/non-string.
 */
export function slugifyModName(name) {
  if (typeof name !== 'string') return '';
  let s = name.trim();
  if (!s) return '';
  // Strip leading + and placeholder chars (#, %).
  s = s.replace(/^\+/, '').replace(/#/g, '').replace(/%/g, '');
  s = s.toLowerCase();
  for (const [src, dst] of SUBSTITUTIONS) s = s.split(src).join(dst);
  // Replace non-alphanumeric runs with `_`. Collapse + trim.
  s = s.replace(/[^a-z0-9_]+/g, '_').replace(/_+/g, '_');
  return s.replace(/^_+|_+$/g, '');
}

/**
 * Resolve a mod input (display name or already-an-id) to its
 * canonical id. Lookup-first: if `nameToId[input]` exists, use it
 * (this is the curated table from mod_ids.json, source of truth).
 * Otherwise slugify and return — covers fresh names that haven't
 * been folded into the table yet.
 *
 * Returns null only if the input is empty or non-string.
 *
 * @param {string} input            display name OR id.
 * @param {Object<string,string>} [nameToId] curated map.
 * @returns {string|null}
 */
export function resolveModId(input, nameToId) {
  if (typeof input !== 'string' || !input.trim()) return null;
  if (nameToId && Object.prototype.hasOwnProperty.call(nameToId, input)) {
    return nameToId[input];
  }
  // Maybe it's already an id (passed through from a saved craft).
  if (/^[a-z][a-z0-9_]*$/.test(input)) return input;
  return slugifyModName(input);
}

/**
 * Split a "TYPE:rest" wishlist/pool key into { type, rest }. Returns
 * `{ type: null, rest: input }` if there's no colon.
 */
export function splitTypedKey(key) {
  if (typeof key !== 'string') return { type: null, rest: '' };
  const i = key.indexOf(':');
  if (i < 0) return { type: null, rest: key };
  return { type: key.slice(0, i), rest: key.slice(i + 1) };
}

/**
 * Resolve a "TYPE:modName" key to its canonical "TYPE:id" form.
 * Returns the input unchanged if it's not the typed-key shape.
 */
export function resolveTypedKey(key, nameToId) {
  const { type, rest } = splitTypedKey(key);
  if (!type) return key;
  const id = resolveModId(rest, nameToId);
  return id ? `${type}:${id}` : key;
}
